"""Small, explicit UI translations; never translate executable source or identifiers."""

import re
from functools import partial

from .teaching import get_teaching_material
from .teaching_en import english_material


EN = {
    "Changing N / 改变 N": "Changing N",
    "Invalid N / 非法 N": "Invalid N",
    "Real SDK delegation / SDK 委派": "Real SDK delegation",
    "Computed evidence / 计算证据": "Computed evidence",
    "Replay rejected / 拒绝重放": "Replay rejected",
    "Tool allowlist / 工具白名单": "Tool allowlist",
    "Evidence beats confidence / 证据胜过置信度": "Evidence beats confidence",
    "Repair and terminate / 修复并停止": "Repair and terminate",
    "Bounded failure / 有界失败": "Bounded failure",
    "Graph execution / 图驱动执行": "Graph execution",
    "Missing relation / 缺失关系": "Missing relation",
    "Cross-run retrieval / 跨次检索": "Cross-run retrieval",
    "Freshness / 数据失效": "Freshness",
    "Grounded knowledge / 有证据的知识": "Grounded knowledge",
    "Invalid range / 非法值域": "Invalid range",
    "Recover known effect / 恢复已知效应": "Recover known effect",
    "Positivity / 共同支持": "Positivity",
    "Falsify revenue-only objective / 否证收入目标": "Falsify revenue-only objective",
    "Negative control / 阴性对照": "Negative control",
    "单条 SELECT/WITH，通过应用层只读守卫": "One SELECT/WITH statement; passed the application read-only guard",
    "离线 function call选择了 ": "The offline function call selected ",
    " 个收入最高的类别：": " highest-revenue categories: ",
    "agent.md 生成的两个 Codex 子智能体已按离线协议模拟依次完成读取与计算：": "Two Codex subagents generated from agent.md completed reading and calculation in the offline protocol simulation: ",
    "离线 OmniGenT harness 模拟的两个 Codex 子智能体完成读取、计算与评估：": "Two Codex subagents simulated by the offline OmniGenT harness completed reading, calculation and evaluation: ",
    "Ralph loop 检查全部 ": "Ralph loop inspected all ",
    " 张表后满足停止条件：": " tables and satisfied the stopping condition: ",
    "本体约束和数据库映射已验证；语义知识页仅包含通过的关系。": "Ontology constraints and database mappings were validated; semantic knowledge pages contain only accepted relations.",
    "门店差异是观察性关联，不是因果效应。store_location、需求和定价可能是混杂因素；要识别库存对收入的因果效应，需要随机/准实验或更完整的时间序列控制。": "Store differences are observational associations, not causal effects. Store location, demand and pricing may confound them. Identifying inventory effects requires randomized/quasi-experiments or more complete time-series controls.",
    "合成实验 / Synthetic experiment": "Synthetic experiment",
    "Agent Kung-fu：初始化与 Demo 目录": "Agent Kung-fu: setup and demo catalog",
    '首次使用先在项目根目录运行 `python -m pip install -e ".[harness,eval,dev]"`，': 'First run `python -m pip install -e ".[harness,eval,dev]"` from the project root.',
    "确认 `data/sakila.db` 存在，再检查下面的环境状态。": "Confirm that `data/sakila.db` exists, then review the environment checks below.",
    "点击目录中各课的 **index**，进入该 demo 的独立页面：": "Select a lesson's **index** to open its independent demo page:",
    "理解控制权变化 → 阅读架构与真实源码 → 预测 → 执行 → 观察轨迹 → 自动验收 → 练习": "Understand control → Read architecture and source → Predict → Run → Observe → Check → Practice",
    "一句话概括十层：L1 让 LLM 按流程工作，L2 让 Agent 执行代码，L3 让 Agent 通过协议协作，": "L1 directs a workflow; L2 grants code capabilities; L3 coordinates through protocols;",
    "L4 让 Agent 处理冲突，L5 让 Agent 通过反馈迭代，L6 让 Agent 操作结构化协同关系，": "L4 enforces boundaries; L5 iterates with feedback; L6 executes graph relationships;",
    "L7 让 Agent 积累知识，L8 让 Agent 按 Ontology 生产知识，L9 让 Agent 建模因果问题，": "L7 persists knowledge; L8 produces ontology-guided knowledge; L9 models causal questions;",
    "L10 让 Agent 从第一性原理重新定义问题并产生创新。": "L10 reframes objectives and tests first-principles mechanisms.",
    "每个 demo 都有独立目录和 index，点击进入后只展示该课。运行结果在本课点击 **Run lesson** 后生成。": "Each demo has its own directory and index. Open one lesson, then select **Run lesson** to generate its results.",
    "十层路线图": "Ten-level roadmap",
    "L1–L5 是 Agent Execution & Control Layer；L6–L10 是 Agent Intelligence Layer。": "L1–L5 cover agent execution and control; L6–L10 cover agent intelligence.",
    "十层的主导驱动、控制对象与核心技术举例": "Drivers, control targets and technology examples",
    "提示词 / Prompt": "Prompt",
    "Token / 上下文": "Tokens / context",
    "技能 / 代码": "Skills / code",
    "工具 / 代码": "Tools / code",
    "智能体通信": "Agent communication",
    "智能体行为": "Agent behavior",
    "智能体轨迹": "Agent traces",
    "数据 / 协同": "Data / collaboration",
    "知识积累": "Knowledge accumulation",
    "概念 / 类型 / 关系": "Concepts / types / relations",
    "问题 / 原因 / 结果": "Questions / causes / outcomes",
    "假设 / 定律 / 原理": "Assumptions / laws / principles",
    "Baseline/L1–L10 可运行": "Baseline and L1–L10 are available",
    "先修复数据库/依赖": "Repair the database or dependencies first",
    "仅 live 模式": "Live mode only",
    "live 模式不可用": "Live mode unavailable",
    "L7–L10 离线也写文件": "L7–L10 write artifacts in offline mode too",
    "数据库未就绪，无法读取表规模。": "Database unavailable; table sizes cannot be read.",
    "关键表规模（实时读取）": "Key table sizes (queried now)",
    "可执行前置检查": "Environment checks",
    "Offline 是确定性教学路径，不等于 mock：数据库、Polars、图构建和文件生成均真实执行。": "Offline mode is deterministic: database queries, Polars, graph construction and artifact generation still execute.",
    "环境检查（初始化说明见总目录）": "Environment checks (setup instructions in the catalog)",
    "先验证环境，再开始实验": "Verify the environment before running",
    "“只读”指所有 SQL 经过应用层单条 `SELECT/WITH` 守卫；SQLite 文件本身并非以 `mode=ro` 打开。": "Read-only refers to the application guard for single SELECT/WITH statements; SQLite itself is not opened with mode=ro.",
    "仅实时模式需要 ollama serve。": "Only live mode requires ollama serve.",
    "仅实时模式需要安装该模型。": "Only live mode requires this model.",
    "L7–L10 离线运行也会写入这里。": "L7–L10 also write here in offline mode.",
    "本地教学运行时": "Local teaching runtime",
    "确认 data/sakila.db、依赖与 YAML 路径。": "Check data/sakila.db, dependencies and YAML paths.",
    "核心本地依赖已就绪，可以运行。": "Core local dependencies are ready.",
    "核心环境未就绪；先按表中建议修复。": "Core environment unavailable; follow the recovery instructions.",
    "相对上一层，控制权发生了什么变化？": "What changes from the previous level?",
    "按步骤理解实现": "Understand the implementation step by step",
    "图是源码调用关系的阅读地图": "A map of source-code calls",
    "Run 前要观察什么？": "What to watch before running",
    "概念检查清单": "Concept checklist",
    "先读懂事实源": "Understand the source of truth",
    "收入链为 `category → film_category → inventory → rental → payment`。下图只用于教学；运行时 schema 始终来自本地 SQLite。": "Revenue follows `category → film_category → inventory → rental → payment`. These diagrams explain the database; execution reads the live SQLite schema.",
    "找出收入最高的电影类别，并说明结果。": "Find the highest-revenue film categories and explain the results.",
    "业务问题（Baseline 忽略；L1–L5 会附加 Top N）": "Business question (ignored by Baseline; L1–L5 append Top N)",
    "运行前预测": "Predict before running",
    "先不作答": "Skip for now",
    "先预测，再执行": "Predict, then execute",
    "离线模式仍执行真实数据库/Polars/图/文件生成。关闭离线后才调用 Ollama；L3 会启动两个 Codex SDK threads；Live L4 还需要 OMNIGENT_URL 与在线 Codex runner（可由 OMNIGENT_RUNNER_ID 固定），并通过 OmniGenT bundle 调用两个 Codex 子智能体。Live L5 以 16 次逐表检查和 1 次收入计算组成 17 轮 Ralph loop，每轮恰好调用一个 Codex agent tool。": "Offline mode executes database queries, Polars, graphs and artifact generation. Live mode calls Ollama; L3 starts two Codex SDK threads. Live L4 requires OMNIGENT_URL and an online Codex runner (optionally OMNIGENT_RUNNER_ID). Live L5 runs 16 inspections and one calculation, with one Codex agent-tool call per iteration.",
    "完成预测后点击 Run lesson。运行结果会保留；调整输入后会显示“结果已过期”，不会偷偷重跑。": "Select Run lesson after making a prediction. Results retain their input snapshot; changing controls marks them stale until you run again.",
    "回到 Setup 检查数据库与依赖；实时连接失败时可切回 Offline teaching mode。": "Check the database and dependencies in Setup. If a live connection fails, switch back to offline teaching mode.",
    "控件已改变；下面仍是上一次运行快照。再次点击 Run lesson 才会更新。": "Controls changed. This is the previous run's snapshot; select Run lesson to update it.",
    "结果与当前控件一致。": "Results match the current controls.",
    "Baseline 已建立：完整类别收入表是后续 L1–L10 的确定性参照。": "Baseline established: the complete category-revenue table is the deterministic reference for L1–L10.",
    "本层没有生成文件；L7 起会出现持久知识工件。": "No artifacts at this level; persistent knowledge artifacts begin at L7.",
    "本层没有协议消息；L3 起可观察 correlation_id。": "No protocol messages at this level; correlation_id appears from L3.",
    "本课没有预测题。": "This lesson has no prediction question.",
    "预测题解析": "Prediction explained",
    "预测正确": "Correct prediction",
    "预测与证据不同": "Prediction differs from the evidence",
    "Level 5 没有取得可交付的停止证明。": "L5 did not establish a valid stopping proof.",
    "/16 张表后，在第 ": "/16 tables inspected; iteration ",
    " 轮通过 baseline parity 并立即退出；收入链=": " passed baseline parity and stopped immediately; revenue chain=",
    "；真实 Codex calls=": "; actual Codex calls=",
    "完成练习后重新运行并比较检查表。下一课建议：Level ": "Rerun after the exercises and compare checks. Suggested next lesson: Level ",
    "离开 Marimo 也能复现": "Reproduce outside marimo",
    "在隔离临时目录执行正常、错误或阴性对照；L9–L10 的效应与创新结果来自合成模型。模型服务不参与本实验。": "Run normal, failure or negative controls in an isolated temporary directory. L9–L10 effects and innovation results come from synthetic models. This experiment does not call a model service.",
    "能力干预实验 / Capability experiment": "Capability experiment",
    "运行能力干预实验 / Run capability experiment": "Run capability experiment",
    "能力实验 / Capability experiment": "Capability experiment",
    "Top N（L1–L5）": "Top N (L1–L5)",
    "导读": "Guide",
    "配置": "Configuration",
    "查询": "Query",
    "执行器": "Runner",
    "数据入口": "Data access",
    "提示词": "Prompt",
    "完整实现": "Implementation",
    "离线模型边界 · SDK 仍真实执行": "Offline model boundary · the SDK still executes",
    "共享状态": "Shared state",
    "复用": "Reuse",
    "角色清单": "Role manifest",
    "动态工厂": "Dynamic factory",
    "可执行 JSON-RPC 边界": "Executable JSON-RPC boundary",
    "协议记录": "Protocol trace",
    "探索状态": "Exploration state",
    "类型化动作": "Typed actions",
    "停止评价器": "Stop evaluator",
    "目录入口": "Package entry",
    "Harness 类型契约": "Typed harness contract",
    "Wiki 生成器": "Wiki generator",
    "Ontology 生成器": "Ontology generator",
    "因果实验": "Causal experiment",
    "完整 runtime": "Complete runtime",
    "路径与连接配置": "Paths and connection configuration",
    "16 类收入基准": "16-category revenue baseline",
    "用户问题": "User question",
    "LangGraph 三步数据流": "LangGraph three-step data flow",
    "Top-N 证据": "Top-N evidence",
    "共享 Polars Workspace": "Shared Polars workspace",
    "证据化回答": "Evidence-based answer",
    "问题 + Top-N": "Question + Top-N",
    "解析并绑定 Codex runner": "Resolve and bind Codex runner",
    "校验路径 + SHA-256": "Validate paths + SHA-256",
    "上传 agent bundle": "Upload agent bundle",
    "只读 Sakila": "Read-only Sakila",
    "委派 · 权限 · 顺序 · 基数 · baseline": "Delegation · permissions · order · cardinality · baseline",
    "拒绝交付": "Reject delivery",
    "仍有未检查表?": "Uninspected tables remain?",
    '"是"': '"Yes"',
    '"否"': '"No"',
    "业务任务": "Business task",
    "运行经验": "Execution experience",
    "共享记忆注入": "Inject shared memory",
    "结果 + durable knowledge": "Result + durable knowledge",
    "问题已识别?": "Problem identified?",
    "关联、假设与实验建议": "Associations, assumptions and experiment proposals",
    "原始问题": "Original question",
    "重新定义目标": "Reframe objective",
    "拆到基本事实": "Decompose into facts",
    "质疑现有假设": "Challenge assumptions",
    "推导最小机制": "Derive minimal mechanism",
    "形成可证伪假设": "Form falsifiable hypotheses",
    "实验与护栏": "Experiments and guardrails",
    "新证据反馈": "New evidence feedback",
    "创新机制 / 新知识": "New mechanisms / knowledge",
    "3（含 evaluator）": "3 (including evaluator)",
    "按表生成 5 个": "5 (one per table)",
    "检索指纹相同的版本": "Retrieve a version with the same fingerprint",
    "无条件复用旧结果": "Reuse old results unconditionally",
    "是，无环": "Yes, acyclic",
    "否，有环": "No, cyclic",
    "无法判断": "Cannot determine",
    "Demo 总目录": "Demo catalog",
    "Demo 目录": "Demo catalog",
    "本 Demo 索引": "Demo contents",
    "本课索引": "Lesson contents",
    "上一课": "Previous",
    "下一课": "Next",
    "架构图": "Architecture",
    "代码说明": "Code guide",
    "运行实验": "Run experiment",
    "运行结果": "Results",
    "能力实验": "Capability experiment",
    "入口": "Entry",
    "等待实验": "Ready to run",
    "实验失败": "Experiment failed",
    "自动检查": "Checks",
    "逐步运行记录": "Execution journal",
    "答案与数据证据": "Answer and evidence",
    "全表探索": "Table exploration",
    "停止评价": "Stop evaluation",
    "Ralph 轨迹": "Ralph trace",
    "步骤": "Step",
    "要做什么": "Action",
    "预期证据": "Expected evidence",
    "项目": "Item",
    "状态": "Status",
    "解析值": "Resolved value",
    "恢复建议": "Recovery",
    "检查": "Check",
    "实际": "Actual",
    "影响": "Impact",
    "说明": "Detail",
    "顺序": "Order",
    "行数": "Rows",
    "列数": "Columns",
    "收入链": "Revenue chain",
    "收入线索": "Revenue signals",
    "轮次": "Iteration",
    "动作": "Action",
    "对象": "Target",
    "反馈摘要": "Feedback digest",
    "Skill摘要": "Skill digest",
    "得分": "Score",
    "评价反馈": "Evaluation feedback",
    "决策": "Decision",
    "期望": "Expected",
    "失败后怎么做": "Recovery",
    "运行证据": "Evidence",
    "意义": "Meaning",
    "你的问题": "your question",
    "表": "Table",
    "并行": "Parallel",
    "协议": "Protocol",
    "冲突": "Conflict",
    "迭代": "Iteration",
    "结构": "Structure",
    "知识": "Knowledge",
    "语义": "Semantics",
    "因果": "Causality",
    "创新": "Innovation",
    "执行 SQL": "Execute SQL",
    "排序": "Sort",
    "对账": "Reconcile",
    "完整基准规模": "Complete baseline size",
    "榜首与金额": "Leading category and revenue",
    "总收入不丢失": "Total revenue preserved",
    "五张源表基数": "Five source-table row counts",
    "完整支付链": "Complete payment chain",
    "LLM 只控制 N": "The LLM only controls N",
    "一主两专": "One manager, two specialists",
    "状态依赖顺序": "State-dependent ordering",
    "大数据不穿过消息": "Large datasets stay outside messages",
    "agent.md 驱动角色": "Roles from agent.md",
    "live 为真实 app-server，offline 为显式模拟": "Real app-server in live mode; explicit simulation offline",
    "A2A / JSON-RPC / MCP 边界": "A2A / JSON-RPC / MCP boundaries",
    "跨消息追踪请求": "Trace requests across messages",
    "能力说明可追溯": "Traceable skill instructions",
    "OmniGenT 定义两个 Codex 角色": "OmniGenT defines two Codex roles",
    "host allowlist 顺序": "Host allowlist ordering",
    "失败即阻止交付": "Failure blocks delivery",
    "目录快照按 canonical 顺序完整推进": "Complete canonical catalog traversal",
    "前轮评价与已加载 skill 同时绑定下一 action": "The next action binds prior feedback and the loaded skill",
    "live 与 simulated 边界可核验": "Verifiable live/simulated boundary",
    "展示声明边界，不把声明误写成跨平台强制保证": "Declared boundaries are not cross-platform enforcement guarantees",
    "全表覆盖后才允许收入计算": "Calculate revenue only after full table coverage",
    "通过 baseline parity 后立即有界退出": "Stop immediately after baseline parity",
    "权限与预算类型化": "Typed permissions and budgets",
    "关系结构可计算": "Computable relationships",
    "跨表协同路径": "Cross-table path",
    "任务图实际调度 Polars": "The task graph actually schedules Polars",
    "知识持久化": "Persistent knowledge",
    "可读、可 diff": "Readable and diffable",
    "跨次检索与指纹失效": "Cross-run retrieval and fingerprint invalidation",
    "知识服从证据": "Knowledge follows evidence",
    "语义资产组合": "Semantic assets",
    "本体指导知识生产": "Ontology-guided knowledge production",
    "语法合法不替代证据": "Syntax does not replace evidence",
    "本体约束控制发布": "Ontology constraints gate publication",
    "观察性对比": "Observational comparison",
    "显式假设": "Explicit assumptions",
    "观察关联 ≠ 因果效应": "Observed association is not a causal effect",
    "暴露识别缺口": "Expose identification gaps",
    "已知真值检验分层调整": "Test stratified adjustment against known truth",
    "重新定义可度量目标": "Reframe a measurable objective",
    "从不变量推导": "Derive from invariants",
    "创新必须能失败": "Innovation must be falsifiable",
    "实际比较净贡献": "Compare measured net contribution",
    "允许没有改善": "Allow no improvement",
}

_PATTERN = re.compile("|".join(re.escape(key) for key in sorted(EN, key=len, reverse=True)))


def translate(value, language="zh"):
    if language != "en":
        return value
    if isinstance(value, str):
        return _PATTERN.sub(lambda match: EN[match.group()], value)
    if isinstance(value, list):
        return [translate(item, language) for item in value]
    if isinstance(value, dict):
        return {translate(key, language): translate(item, language) for key, item in value.items()}
    return value


def material_for_language(level, language="zh"):
    material = get_teaching_material(level)
    return (
        english_material(material, partial(translate, language=language))
        if language == "en"
        else material
    )


def demo_url(level=None, *, language="zh", anchor=""):
    folder = "baseline" if level == 0 else f"level_{level:02d}" if level is not None else ""
    path = f"/{folder}/index/" if folder else "/"
    return f"{path}?lang={language}" + (f"#demo-{anchor}" if anchor else "")
